name: ci

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  DOTNET_NOLOGO: true

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Install tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore src/Apologist/Apologist.csproj

      - name: Build
        run: dotnet build src/Apologist/Apologist.csproj --no-restore -c Release

      - name: Restore test dependencies
        run: dotnet restore src/Apologist.Test/Apologist.Test.csproj

      - name: Build tests
        run: dotnet build src/Apologist.Test/Apologist.Test.csproj --no-restore -c Release

      - name: Test
        run: dotnet test src/Apologist.Test/Apologist.Test.csproj --no-restore --no-build -c Release

      - name: Pack
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: dotnet pack src/Apologist/Apologist.csproj --no-build --no-restore -c Release

      - name: NuGet login (OIDC → temp API key)
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Publish to NuGet.org
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: >
          dotnet nuget push src/Apologist/bin/Release/*.nupkg
          --api-key ${{ steps.login.outputs.NUGET_API_KEY }}
          --source https://api.nuget.org/v3/index.json
          --skip-duplicate
